.gitignore, images/Dockerfile, servers-management/dell/ansible/README.md, servers-management/dell/ansible/dell_setup.yaml, servers-management/dell/ansible/idrac_vars.example.yaml, servers-management/dell/ansible/inventory.yaml
Ansible playbook to orchestrate the setup of the Dell Servers located at RDU2 and managed by the CI for testing OCP so that their configuration is kept consistent with the requirements for testing.
Implements [OCPQE-14115](https://issues.redhat.com//browse/OCPQE-14115)
=> Add ansible playbook to setup the Dell servers in RDU2 lab

images/bind9/Dockerfile, images/bind9/root/etc/bind/named.conf.default-zones, images/bind9/root/etc/bind/named.conf.options, images/bind9/root/etc/named.conf, images/fcos-bastion-image/root/usr/lib/systemd/system-preset/98-bastion.preset, images/fcos-bastion-image/root/usr/lib/systemd/system/bind9.service
This code expects the following files:
- /opt/bind9/named.conf.local
- /opt/bind9/named.conf.deployment_options
- zones-specific files (as reported in the /opt/bind9/named.conf.local file)
to be provided externally
=> OCPQE-15781: Adding bind9.service

images/fcos-bastion-image/root/usr/lib/systemd/system-preset/98-bastion.preset
Adding missing `tang.service` preset within `images/fcos-bastion-image/root/usr/lib/systemd/system-preset/98-bastion.preset` to enable the service by default.
=> OCPQE-16616: Adding missing tang.service enabled preset

images/prow-image/Dockerfile
To allow multi-arch builds and also removes packages we finally decided not to use.
=> Refine base image to allow multi-arch builds and remove unneeded packages

images/fcos-base-image/root/usr/bin/libvirt_init.sh, images/fcos-base-image/root/usr/lib/NetworkManager/conf.d/99-no-resolved.conf, images/fcos-base-image/root/usr/lib/systemd/system-preset/00-systemd-override.preset, images/fcos-base-image/root/usr/lib/systemd/system-preset/97-fedora-custom.preset, images/fcos-base-image/root/usr/lib/systemd/system/fix-resolvconf.service, images/fcos-base-image/root/usr/lib/systemd/system/libvirtd-initial.service
This PR:
- improves and fix a minor issue in the libvirt-init unit (cc @zniu1011)
- fixes bind9 never started as a unit in fcos as resolved preempts port 53 (cc @jadhaj )
=> OCPQE-15775: Fixes

images/fcos-base-image/Containerfile, images/fcos-bastion-image/root/usr/bin/gen_registry_file.sh, images/fcos-bastion-image/root/usr/lib/systemd/system/registry@.service, images/fcos-bastion-image/root/usr/share/bastion_services/ignitions/wipe_disks.bu
- The registries need an env file to provide credentials for the registry mirroring config
- The wipe-fs unit should consider SSDs too. Moreover, we'd allow it to fail to avoid the hosts getting stuck on failures
- Install `tree`
- Disables rpmfusion-nonfree as (1) we don't use any package from that repo, (2) is undergoing a failure at the time of writing due to some updates of the content and the calculation of the checksums.
Related to [OCPQE-18431](https://issues.redhat.com//browse/OCPQE-18431)
=> OCPQE-18431: Minor fixes

images/fcos-bastion-image/root/usr/bin/prepare_host_for_boot
This PR fixes a bug with hpe ARM servers that would always mount and boot from the ipxe image regardless of the configured boot mode
=> [OCPQE-18644] - use ipxe on hpe arm servers only when boot mode is pxe

images/fcos-bastion-image/Containerfile
The PR addresses jira ticket https://issues.redhat.com/browse/OCPQE-18643
=> OCPQE-18643: Add python3 deps required to run pruning

images/fcos-bastion-image/root/usr/bin/dhcp-init.sh, images/fcos-bastion-image/root/usr/lib/systemd/system/dhcp.service, images/fcos-bastion-image/root/usr/share/bastion_services/dhcp/dnsmasq.conf
Use dhcp-hostsdir and dhcp-optsdir
These options help to avoid dnsmasq restarts by dynamically adding new
entries and changes. It only needs a SIGHUP when entries are deleted.
Enabled dnsmasq.leases to see the current active leases if needed while
debugging. The SIGHUP does not update this file.
Tested the options.
1. set the mac to ip address 192.168.123.55
2. Requested IP and received address 192.168.123.55 on a container
2. Deleted container, updated IP address to 192.168.123.67 in the hostsdir file
3. Started a new container
4. Sent a SIGHUP to dnsmasq process
5. Requested for IP and received IP 192.168.123.67 for the same mac
```
interface=br-int
dhcp-hostsdir=/var/lib/hosts/hostsdir
dhcp-optsdir=/var/lib/hosts/optsdir
dhcp-range=192.168.123.50,192.168.123.75,6h …
```
=> OCPQE-18500: use dhcp-hostsdir=<path> in dnsmasq for dynamic updates

images/fcos-bastion-image/root/usr/bin/clean-registries.sh, images/fcos-bastion-image/root/usr/lib/systemd/system-preset/98-bastion.preset, images/fcos-bastion-image/root/usr/lib/systemd/system/clean-registries.service, images/fcos-bastion-image/root/usr/lib/systemd/system/clean-registries.timer
The purpose of this PR is to create a timer unit that loops over all the enabled registries@ template units and clean up the mirrored container images.
=> OCPQE-19170: Add timer unit for registries cleanup

images/fcos-bastion-image/root/usr/share/bastion_services/dhcp/dnsmasq.conf
As dhcp-boot override, especially when used in dhcp-optsdir
=> Remove dhcp-boot, use dhcp option 67 (bootfile-name)

images/fcos-base-image/root/usr/bin/libvirt_init.sh
libvirt spawns its own dnsmasq instance listening at 192.168.122.1:53, since the port-forwarding on the bind9 container is set to all the IPs, if libvirt is initialized before bind9, bind9 can't start as can't bind to port *:53.
=> Disable libvirt default network

images/fcos-bastion-image/root/usr/lib/systemd/system/registry@.service
The registry@ services become unhealthy and get killed after a while they started.
This is due to distribution/distribution-library-image#158. The healthchecks are based on wget, and wget leaks a defunct process everytime the healthcheck launches. Eventually, we reach the ulimit, no more forks are allowed and the container is restarted.
This commit changes the healtcheck to use curl, that is installed by the healthcheck itself if not already available. This is a workaround to revert once a fix for distribution/distribution-library-image#158 lands and a new image is published.
=> OCPQE-19722: Fix registry@.service healthchecks

images/fcos-bastion-image/root/usr/bin/mount.vmedia.ipxe, images/fcos-bastion-image/root/usr/bin/prepare_host_for_boot
For arm64 hpe hosts the vmedia does not seem to get ejected after the
first boot causing the hosts to boot via pxe on every boot and failing
install. This should set the pxe enabled via vmedia to be used only
once.
Remove setting of one-time boot from mount.vmedia.ipxe to keep it
specific to mounting while prepare_host_for_boot does this setting.
=> OCPQE-18644: Set BootSourceOverrideEnabled once

images/fcos-base-image/root/usr/bin/cache-clean-ipi.sh, images/fcos-base-image/root/usr/lib/systemd/system/cache-clean-ipi.service, images/fcos-base-image/root/usr/lib/systemd/system/cache-clean-ipi.timer, images/fcos-bastion-image/root/usr/bin/clean-up.sh, images/fcos-bastion-image/root/usr/lib/systemd/system/nodes-pruner.timer
Timer is set to run 30 mins past the hour, every 3 hours to delete any
iso files not used for more than 15 days.
Additional updates
Nodes pruner was set to run every 2 mins. This PR updates to run 2 minutes past
every hour.
Include tag for color in logs
=> OCPQE-19171: Cleanup timer unit for the ipi cached ISO

images/fcos-bastion-image/root/usr/bin/hpecmd
Utility script allowing to run commands inside the HPe iLO shell from the bastion host, useful to retrieve SoL logs (workarounds ipmitool incompatibility)
Usage: `hpecmd <host_id> <command>`
=> [OCPQE-18591] - add hpecmd for hpe SoL support

images/fcos-bastion-image/root/usr/bin/clean-up.sh
Enable setting an expiry date for persistent clusters in ISO 8601 and
UTC format, or keep the cluster persistent forever with an empty preseve
file
=> OCPQE-23078: setup an expiry date for persistent clusters

images/prow-image/root/usr/bin/deprovision.sh
This fixes the unbound variable errors and cleanup of firewall is always executed. 'FIREWALL' variable does not exist
=> Fix var for firewalled cluster and export arch

images/fcos-bastion-image/root/usr/lib/systemd/system/registry@.service
This PR proposes to increase the delay between health-checks and adds further delay to avoid immediate re-execution on failure and allow temporary issues due to overload from letting podman considering the registry failed and restarting it.
=> OCPQE-20708: Increase retrials and delay between health-checks for registry@

images/fcos-bastion-image/root/usr/bin/clean-up.sh
find /var/builds/ -maxdepth 1 -type d -mmin +1440 -print0
/var/builds/ci-op-693k5mg2/var/builds/ci-op-x0m0ht9s#              
find /var/builds/ -maxdepth 1 -type d -mmin 1440+ -print0
find: invalid argument `1440+' to `-mmin'
=> fix nmin incorrect argument

images/fcos-bastion-image/root/usr/bin/clean-up.sh, images/fcos-bastion-image/root/usr/lib/systemd/system/nodes-pruner.service, images/fcos-bastion-image/root/usr/lib/systemd/system/nodes-pruner.timer, images/fcos-bastion-image/root/usr/lib/systemd/system/podman-pruner.service, images/fcos-bastion-image/root/usr/lib/systemd/system/podman-pruner.timer
Timer will run daily at 6 am
PR also updates logs and comments for deleting clusters older than `24h` from previouly set `3 days`
=> OCPQE-25546: Add timer service to cleanup podman unused resources

images/fcos-bastion-image/root/usr/bin/clean-up.sh
below scripys:
bash ./wipe/baremetal-lab-post-wipe-commands.sh
bash ./dns/baremetal-lab-post-dns-commands.sh
bash ./firewall/baremetal-lab-post-firewall-commands.sh
bash ./load-balancer/baremetal-lab-post-load-balancer-commands.sh
contains the following  code snippet:
[ -z “${PULL_NUMBER:-}” ] && \
timeout -s 9 10m ssh “${SSHOPTS[@]}” “root@${AUX_HOST}” \
test -f /var/builds/${NAMESPACE}/preserve && \
exit 0
which causes them to exit 0 early, due to the existence of preserve file, hence actual pruning will not happen
The PR propose to delete preserve file once a decision is taken to prune the cluster, before calling prune_nodes
=> Remove preserve file before calling prune_nodes

images/fcos-base-image/Containerfile, images/fcos-bastion-image/root/usr/bin/clean-up.sh, images/prow-image/root/usr/bin/deprovision.sh
Many cluster installs failed recently as 3-4 host had dhcp entries for a
non existing cluster. This PR will check for such occurrence and do a
cleanup.
Add INTERNAL_NET_CIDR for prune_nodes
This is needed for clean up of disconnected jobs
=> OCPQE-28188: Check and clean up leftover dhcp entries
